version: "3"
services:
  database:
    image: postgres:latest
    ports:
      - 6543:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Anna_098!
      POSTGRES_DB: postgresForTests